frontend:
  banner_left: "banner_left"
  banner_middle: "banner_middle"

  favorite_recipes: "favorite_recipes"
  tip_recipes: "tip_recipes"

  home_page: "home"

recipe_form:
  default_step: "1"

recipe_index_type:
  posted: "posted"
  draft: "draft"

rating:
  max_rating: 5
